config/routes.rb
Rails.application.routes.draw do
  root to: 'todos#index'
  devise_for :users
  resources :users
  resources :todos
end

app/models/todo.rb
class Todo < ActiveRecord::Base
  belongs_to :creator, class_name: "User"
  has_and_belongs_to_many :performers,
                          class_name: "User",
                          foreign_key: "todo_id",
                          association_foreign_key: "user_id"
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  has_many :todos, foreign_key: "creator_id"
  has_and_belongs_to_many :assigned_tasks,
                          class_name: "Todo",
                          foreign_key: "user_id",
                          association_foreign_key: "todo_id"

  def all_todos
    (todos + assigned_tasks).uniq
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
  before_action :authenticate_user!
end

app/controllers/registrations_controller.rb
class RegistrationsController < Devise::RegistrationsController

  private

  def sign_up_params
    params.require(:user).permit(:name, :email, :password, :password_confirmation)
  end

  def account_update_params
    params.require(:user).permit(:name, :email, :password, :password_confirmation, :current_password)
  end
end

app/controllers/todos_controller.rb
class TodosController < ApplicationController

  before_action :set_todo, only: [:show, :edit, :update, :destroy]

  def index
    @todos = current_user.all_todos
  end

  def show
  end

  def new
    @todo = Todo.new
  end

  def edit
  end

  def create
    @todo = Todo.new(todo_params)
    @todo.creator = current_user

    respond_to do |format|
      if @todo.save
        format.html { redirect_to @todo, notice: 'Todo was successfully created.' }
        format.json { render :show, status: :created, location: @todo }
      else
        format.html { render :new }
        format.json { render json: @todo.errors, status: :unprocessable_entity }
      end
    end
  end

  def update
    respond_to do |format|
      if @todo.update(todo_params)
        format.html { redirect_to @todo, notice: 'Todo was successfully updated.' }
        format.json { render :show, status: :ok, location: @todo }
      else
        format.html { render :edit }
        format.json { render json: @todo.errors, status: :unprocessable_entity }
      end
    end
  end

  def destroy
    @todo.destroy
    respond_to do |format|
      format.html { redirect_to todos_url, notice: 'Todo was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private

  def set_todo
    @todo = Todo.find(params[:id])
  end

  def todo_params
    params.require(:todo).permit(:caption,
                                 :description,
                                 :deadline,
                                 :shared, performer_ids: [])
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController

  def index
    @users = User.all
  end

  def show
    @user = User.find(params[:id])
    unless @user == current_user
      redirect_to :back, :alert => "Access denied."
    end
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/todos_helper.rb
module TodosHelper
end

app/views/layouts/_messages.html.slim
/ Rails flash messages styled for Bootstrap 3.0
- flash.each do |name, msg|
  - if msg.is_a?(String)
    div class="alert alert-#{name.to_s == 'notice' ? 'success' : 'danger'}"
      button.close[type="button" data-dismiss="alert" aria-hidden="true"] ×
      = content_tag :div, msg, :id => "flash_#{name}"

app/views/layouts/_nav_links_for_auth.html.erb
<% if user_signed_in? %>
  <li><%= link_to 'Edit account', edit_user_registration_path %></li>
  <li><%= link_to 'Sign out', destroy_user_session_path, :method=>'delete' %></li>
<% else %>
  <li><%= link_to 'Sign in', new_user_session_path %></li>
  <li><%= link_to 'Sign up', new_user_registration_path %></li>
<% end %>

app/views/layouts/_navigation.html.slim
/ navigation styled for Bootstrap 3.0
nav.navbar.navbar-inverse.navbar-fixed-top
  .container
    .navbar-header
      button.navbar-toggle[type="button" data-toggle="collapse" data-target=".navbar-collapse"]
        span.sr-only Toggle navigation
        span.icon-bar
        span.icon-bar
        span.icon-bar
      = link_to 'TODO SHARE', root_path, class: 'navbar-brand'
    .collapse.navbar-collapse
      ul.nav.navbar-nav.pull-right
        == render 'layouts/nav_links_for_auth'

app/views/layouts/application.html.slim
doctype html
html
  head
    meta[name="viewport" content="width=device-width, initial-scale=1.0"]
    title
      = content_for?(:title) ? yield(:title) : 'Todo Share'
    meta name="description" content="#{content_for?(:description) ? yield(:description) : 'Todo Share'}"
    == stylesheet_link_tag "application", :media => 'all'
    == javascript_include_tag 'application'
    == csrf_meta_tags
  body
    header
      == render 'layouts/navigation'
    main[role="main"]
      == render 'layouts/messages'
      == yield

app/views/todos/_form.html.slim
= simple_form_for @todo do |f|

  = f.input :caption
  = f.input :description
  = f.label :deadline
  = f.input_field :deadline, as: :datetime
  = f.input :shared, as: :boolean
  = f.association :performers, label_method: :name, value_method: :id, include_blank: false

  = f.button :submit

app/views/todos/edit.html.slim
h1 Editing Todo

= render 'form'

= link_to 'Show', @todo
br
= link_to 'Back', todos_path

app/views/todos/index.html.slim
p#notice = notice

h1 My Todos

= link_to 'New Todo', new_todo_path

table.table.table-responsive
  thead
    tr
      th Caption
      th Description
      th Shared
      th Created at
      th Deadline
      th colspan="3"

  tbody
    - @todos.each do |todo|
      tr
        td = todo.caption
        td = todo.description
        td = todo.shared
        td = todo.created_at
        td = todo.deadline
        td = link_to 'Show', todo
        td = link_to 'Edit', edit_todo_path(todo)
        td = link_to 'Destroy', todo, method: :delete, data: { confirm: 'Are you sure?' }

app/views/todos/new.html.slim
h1 New Todo

= render 'form'

= link_to 'Back', todos_path

app/views/todos/show.html.slim
p#notice
  = notice

p
  strong
    ' Created at:
  = @todo.created_at

p
  strong
    ' Caption:
  = @todo.caption

p
  strong
    ' Description:
  = @todo.description

p
  strong
    ' Deadline:
  = @todo.deadline

= link_to 'Edit', edit_todo_path(@todo)
br
= link_to 'Back', todos_path

app/views/users/_user.html.erb
<td><%= link_to user.name, user %></td>
<td><%= link_to user.email, user %></td>

app/views/users/index.html.erb
<div class="container">
  <div class="row">
    <h3>Users</h3>
    <div class="column">
      <table class="table">
        <tbody>
          <% @users.each do |user| %>
            <tr>
              <%= render user %>
            </tr>
          <% end %>
        </tbody>
      </table>
    </div>
  </div>
</div>

app/views/users/show.html.erb
<h3>User</h3>
<p>Name: <%= @user.name if @user.name %></p>
<p>Email: <%= @user.email if @user.email %></p>